[package]
name = "kidfile"
version = "0.3.1"
edition = "2024"

[dependencies]
tim2 = {path = "../tim2-rs/lib"}
image = "0.25.5"
png = "0.17.16"
bytemuck = "1.22.0"
zune-inflate = "0.2.54"
paste = "1.0.15"
